<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtpass</name>
   <tag></tag>
   <elementGuidId>e97e09e8-6b11-4286-8ed4-fbe4be73d7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtpass</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtpass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91165bec-eaa5-427b-9e91-1e06634a2ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtpass</value>
      <webElementGuid>01f54db0-0efc-430f-962c-5e4e0e8667b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d346319f-30e2-4611-95ec-ced49d0d267e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>fc7da73b-adb0-405c-ae44-ef2ac5a16cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtpass</value>
      <webElementGuid>b64e2187-14cf-45c6-8329-e0a1a08e9b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextBox</value>
      <webElementGuid>47786b98-01d2-40c9-88e3-738c3f4ff401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtpass&quot;)</value>
      <webElementGuid>317b24bd-c0a2-4e6a-90f2-8f8fcd2fac6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtpass']</value>
      <webElementGuid>e70b0b26-952f-46b6-b9fb-31bd1f1a74bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/center/div/table/tbody/tr/td/div/table/tbody/tr[4]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a090a1f8-e377-404a-bc84-aba5c213da24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ad08deab-45d2-41a0-bd9c-1e839ae68cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtpass' and @type = 'password' and @id = 'txtpass']</value>
      <webElementGuid>d2e75334-f189-4dca-9aa5-8038a6cc78b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
