<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtusuario</name>
   <tag></tag>
   <elementGuidId>c173227f-8116-4ad3-9f4e-82a7a625d5a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtusuario</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtusuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6db210e-cb2a-4277-82d5-abf267e021a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtusuario</value>
      <webElementGuid>3b0b68f6-3e55-418d-a94b-8c71f2deb4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f4482c5-efe7-41d9-b435-b5e338262b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4ebc71c7-1224-4672-b42f-fbf3e5894859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtusuario</value>
      <webElementGuid>6144d6be-d0bc-44ce-a60a-faf4f5d9ecc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextBox</value>
      <webElementGuid>cf22b1b7-1c10-4381-86f5-23776e696467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtusuario&quot;)</value>
      <webElementGuid>483770b8-4675-4312-b05a-570d48cded55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtusuario']</value>
      <webElementGuid>ccb8ef6a-b23e-42dc-91fc-142f428a29b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/center/div/table/tbody/tr/td/div/table/tbody/tr[3]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>bc6de0e2-d773-497b-9777-9a3f1653ecea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>5f6c80e9-4fb6-40c4-bff1-dde9542d22d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtusuario' and @type = 'text' and @id = 'txtusuario']</value>
      <webElementGuid>b229529a-868d-45a7-b301-59eea8ecb083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
