<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VER CLIENTE</name>
   <tag></tag>
   <elementGuidId>c911d57e-1cb7-4c63-b54e-518f47926f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lk_VerRegistro</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lk_VerRegistro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2151a94-f172-43b6-bb96-3ea3417553d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lk_VerRegistro</value>
      <webElementGuid>ef10d233-8088-4123-976f-283ad2879daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e41b9248-2b5d-4001-a7c9-1d0d95a3f771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lk_VerRegistro&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>86f52199-3042-4885-b045-5649e0e821d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VER CLIENTE</value>
      <webElementGuid>f53cee98-1f8e-4f22-9d8f-6af750e29559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lk_VerRegistro&quot;)</value>
      <webElementGuid>840dd1c6-748a-40d8-b909-3090d4fb564e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lk_VerRegistro']</value>
      <webElementGuid>7d696c3a-7e32-4410-9555-8880a3b30ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Tr2']/td/a</value>
      <webElementGuid>756f282a-d73f-41d1-b6e1-af3fa1b51af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VER CLIENTE')]</value>
      <webElementGuid>3522cd31-2831-4a9b-ba87-3253a1687197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID SERVICIO'])[1]/following::a[1]</value>
      <webElementGuid>8afda70a-e45a-41f4-a74a-291f4d034dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Ingrese información del servicio y luego oprima ', '&quot;', 'ver cliente', '&quot;', '')])[1]/following::a[1]</value>
      <webElementGuid>fa6505f8-be87-4cea-ad80-15f826e1f850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>61bffb0a-78e0-4fd6-a427-31836c4b168f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SE ACEPTAN SÓLO NUMEROS EN EL TEXTO DE BUSQUEDA!'])[1]/preceding::a[1]</value>
      <webElementGuid>7a7e3fbc-08c4-43e9-8f3c-2250df5c9d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VER CLIENTE']/parent::*</value>
      <webElementGuid>490dcf8b-6fea-490c-9ed1-f4712cff1107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lk_VerRegistro&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>d6fd501b-dd76-4bcc-929b-9f524b93308b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>8dc866c8-b651-41a8-91de-ab7f3229d25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lk_VerRegistro' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lk_VerRegistro&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'VER CLIENTE' or . = 'VER CLIENTE')]</value>
      <webElementGuid>149ed71a-93b5-4e36-b1d7-b204004964c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
