<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__texto_Busqueda</name>
   <tag></tag>
   <elementGuidId>b70d7cd4-fcfe-4229-8f27-da628eb329d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#texto_Busqueda</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='texto_Busqueda']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb4aac3a-3255-4b87-a1f6-7ee367587fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>texto_Busqueda</value>
      <webElementGuid>e5346c56-d1f7-49aa-be49-34f46c6ae137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0acf3699-9590-47b7-bac4-bb5d3b2fab49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>texto_Busqueda</value>
      <webElementGuid>4d7cbbe5-3da1-4958-adc6-2a60aa07551d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>5fb24529-684d-4722-be9e-1a1b67523af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;texto_Busqueda&quot;)</value>
      <webElementGuid>714087e7-65db-466e-b323-4fe5d6bfa8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='texto_Busqueda']</value>
      <webElementGuid>b5d7a8cc-f617-4505-bb9b-fbeb6f6641f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='Tr2']/td/input</value>
      <webElementGuid>79693ced-dc57-4328-acf7-3786d681569f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>0e82a260-34b4-465f-85aa-4626b30525d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'texto_Busqueda' and @type = 'text' and @id = 'texto_Busqueda']</value>
      <webElementGuid>d18b741d-169f-45c9-985d-6bdf97f61550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
