<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CORTE</name>
   <tag></tag>
   <elementGuidId>bddb4111-608e-4fec-8f0f-a2229df23a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='GrillaHistorica']/tbody/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9d45b449-5b93-4b4e-82cd-47618e6e5a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CORTE</value>
      <webElementGuid>87fc282f-1da7-4745-bdb9-b32615eeda6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GrillaHistorica&quot;)/tbody[1]/tr[2]/td[1]</value>
      <webElementGuid>fdff025a-c540-4705-a3b3-f7ba5b58cc0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='GrillaHistorica']/tbody/tr[2]/td</value>
      <webElementGuid>84a5a027-bdd5-42c4-be2a-c362add0843d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubicación'])[1]/following::td[1]</value>
      <webElementGuid>f8cbe9f2-f7da-4690-b108-b6a056710f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VISITAS'])[1]/following::td[2]</value>
      <webElementGuid>a2427763-0c1c-4d84-90b7-3d052166447b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPROCEDENTE'])[1]/preceding::td[6]</value>
      <webElementGuid>7440f434-872f-4f99-a7ff-fd7f0dc8afbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASA CERRADA CORTABLE'])[1]/preceding::td[7]</value>
      <webElementGuid>cdb00615-f451-4af2-93ad-8140cb3a38a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CORTE']/parent::*</value>
      <webElementGuid>515aaefd-c3ac-4fbe-bb55-b50b7fad83d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/table/tbody/tr[2]/td</value>
      <webElementGuid>7111728a-11bd-4b9e-a0a9-79524449c869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CORTE' or . = 'CORTE')]</value>
      <webElementGuid>d9c4aada-95d4-416b-95fe-ce7cdd927c48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
