<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Todas las Ordenes de Trabajos ltimos 6 _6ecd49</name>
   <tag></tag>
   <elementGuidId>f17825c3-1211-45c6-9981-b8459264b221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='crmGrid_SavedNewQuerySelector']/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ms-crm-View-icon-associated-lite.ms-crm-ImageStrip-Dropdown_Arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-View-icon-associated-lite ms-crm-ImageStrip-Dropdown_Arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Seleccionar vista</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_imgs/imagestrips/transparent_spacer.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crmGrid_SavedNewQuerySelector&quot;)/span[@class=&quot;ms-crm-View-icon ms-crm-ViewSelector-dropdown-icon-associated-lite&quot;]/img[@class=&quot;ms-crm-View-icon-associated-lite ms-crm-ImageStrip-Dropdown_Arrow&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_rdenes de Trabajo Todas las Ordenes de_4e407a/iframe_Abra esta vista en el editor de vist_8eab21</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='crmGrid_SavedNewQuerySelector']/span[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Seleccionar vista']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
