<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ciclo_xddlCiclo_B-1Img</name>
   <tag></tag>
   <elementGuidId>fac09d52-478f-4060-8632-197309123843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xddlCiclo_B-1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlCiclo_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67ee8509-e366-459e-bc8a-7f248ca0f197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlCiclo_B-1Img</value>
      <webElementGuid>494129a2-bcc0-4d9f-9abe-31663c451194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Office2010Blue</value>
      <webElementGuid>8fdf33b2-b9bf-4366-98c2-783c89045cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_19-zQ8Pb</value>
      <webElementGuid>95343eac-b46e-4b60-a7dc-f1d91766d0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>b412d4e7-0563-444d-9a97-30e8a869addc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlCiclo_B-1Img&quot;)</value>
      <webElementGuid>a13c26f9-f0a6-4629-a749-a6689b90e305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xddlCiclo_B-1Img']</value>
      <webElementGuid>0b6c7dfb-dbfc-4fe4-9a52-067a7711bf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='xddlCiclo_B-1']/img</value>
      <webElementGuid>109027bb-615d-40c2-8414-3b21fc56381d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>0633e5f7-c423-4530-badc-5fd8b0312781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>82365c03-f720-42de-8901-354649942975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'xddlCiclo_B-1Img' and @src = '/DXR.axd?r=1_19-zQ8Pb' and @alt = 'v']</value>
      <webElementGuid>ecba5d53-ab85-440e-a4a7-a71cdefa779c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
