<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hasta_xrpnlLote_xddlLoteHasta_B-1Img (1)</name>
   <tag></tag>
   <elementGuidId>97bc3714-9c8e-4306-ae0f-7afbb7e23605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xrpnlLote_xddlLoteHasta_B-1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xrpnlLote_xddlLoteHasta_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f01b9a62-932d-4d2a-8111-079720eaa03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xrpnlLote_xddlLoteHasta_B-1Img</value>
      <webElementGuid>8faf73ca-37c3-4778-bf18-d37e8d461649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Office2010Blue</value>
      <webElementGuid>6df4d7e9-b3ff-4893-969d-c23bbb1daaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_19-zQ8Pb</value>
      <webElementGuid>edf1cbfa-12ae-426c-b94d-4f27dc52ab2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>61bb9534-3d0f-40bd-b3f8-f57310f3df07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xrpnlLote_xddlLoteHasta_B-1Img&quot;)</value>
      <webElementGuid>b77f4ef8-b6ba-402e-b506-1738ad727747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xrpnlLote_xddlLoteHasta_B-1Img']</value>
      <webElementGuid>a5baa96d-fecf-4c5d-9258-6d86baed00a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='xrpnlLote_xddlLoteHasta_B-1']/img</value>
      <webElementGuid>47f8f358-368c-4c17-a3c7-b6415a410c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[3]</value>
      <webElementGuid>0ec20792-060b-4e2d-9a18-86e2c259ea12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/table/tbody/tr/td[3]/img</value>
      <webElementGuid>0df689d8-4c93-4881-b3a6-64d54eaeb635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'xrpnlLote_xddlLoteHasta_B-1Img' and @src = '/DXR.axd?r=1_19-zQ8Pb' and @alt = 'v']</value>
      <webElementGuid>09faf22b-507f-483c-9024-0d5bfd750625</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
