<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciclo_xddlCiclo</name>
   <tag></tag>
   <elementGuidId>998c2cdd-1b7b-47f1-a794-2d2c07ba26c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xddlCiclo_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlCiclo_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f58c35a6-fbe1-450b-92e8-61d08624bb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys</value>
      <webElementGuid>b2a05a34-1d91-4644-950d-17b38e2f6300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlCiclo_I</value>
      <webElementGuid>f2ea2be1-3bde-43b6-bf52-0025c8952e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xddlCiclo</value>
      <webElementGuid>33f262c9-c38b-4465-8246-0abfc22d1664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('xddlCiclo')</value>
      <webElementGuid>e9c87254-8f73-440c-a1ac-7e47a83eae9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('xddlCiclo')</value>
      <webElementGuid>5a2e62f7-29ae-4489-8232-b8689573b81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('xddlCiclo')</value>
      <webElementGuid>465bada2-10c5-463b-af38-ac2b9f30e186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ciclo 342- (202205)</value>
      <webElementGuid>28f99126-7e13-4dfd-b526-e4e7b531003e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f567a924-8fbe-4b60-b271-39389c76a474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>225d55d5-c26a-4325-b36e-96acbf0ab85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlCiclo_I&quot;)</value>
      <webElementGuid>07d454fd-3661-4580-bae6-de51351344f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xddlCiclo_I']</value>
      <webElementGuid>ffd778ff-f2e5-429f-91b1-0b58f3b7b510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xddlCiclo']/tbody/tr/td[2]/input</value>
      <webElementGuid>c59010ff-3a22-4ae2-9770-0771425a6525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>3a2b8cb8-f4bf-4a6b-9362-7c01b97d17f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xddlCiclo_I' and @name = 'xddlCiclo' and @type = 'text']</value>
      <webElementGuid>42f4176a-5254-43de-88e5-3c27b3e1ae55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
