<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciclo_xddlCiclo (1)</name>
   <tag></tag>
   <elementGuidId>e6ff325e-038f-474e-a1a4-785e3314c42f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xddlCiclo_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlCiclo_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ca75bce-1598-4561-9deb-e6a3a0ae0941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys</value>
      <webElementGuid>81ad1be3-962d-4d56-b6ae-25f5338bc6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlCiclo_I</value>
      <webElementGuid>471297fd-5eee-40c7-9db4-8a748f674126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xddlCiclo</value>
      <webElementGuid>17667f9b-dae7-4186-a5cb-4c6cdc1ac927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('xddlCiclo')</value>
      <webElementGuid>95afa12d-3f0e-49c9-b1df-4997ccb1548f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('xddlCiclo')</value>
      <webElementGuid>82fcd168-a9ab-406c-8fa0-4880ea1fec61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('xddlCiclo')</value>
      <webElementGuid>c56ebd19-10ea-4eb7-a9ba-05c9cc8d0326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ciclo 342- (202205)</value>
      <webElementGuid>9025f4aa-82c9-47fa-83f9-0d01660a7833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab7db8cc-9f46-410e-b9d2-54bfdad4f412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32b53d23-706b-41c1-b099-6621c59e5fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlCiclo_I&quot;)</value>
      <webElementGuid>13273cb4-9db2-48e7-92bb-f8c2445017f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xddlCiclo_I']</value>
      <webElementGuid>f2f4eafe-91ba-4b91-a147-073ff6bbbdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xddlCiclo']/tbody/tr/td[2]/input</value>
      <webElementGuid>bdb7cef4-ff4f-42df-b9df-413b2075d36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>d175673b-95ce-4c69-bf06-f555b553325f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xddlCiclo_I' and @name = 'xddlCiclo' and @type = 'text']</value>
      <webElementGuid>6e6787bb-b89e-43a9-82a4-0c1355dc158a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
