<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Ciclo 284- (202208)</name>
   <tag></tag>
   <elementGuidId>b8056626-0067-46b7-8458-45539915faa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xddlCiclo_DDD_L_LBI1T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlCiclo_DDD_L_LBI1T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>390039f1-c06f-4eb4-aecb-a37b4f6f0ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Office2010Blue dxeListBoxItemHover_Office2010Blue dxeListBoxItemSelected_Office2010Blue</value>
      <webElementGuid>884be52e-353d-4f13-a2ab-ec44d8671787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlCiclo_DDD_L_LBI1T0</value>
      <webElementGuid>7544efaa-7d0a-48a0-a418-bbb748110641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ciclo 284- (202208)</value>
      <webElementGuid>9793681d-1463-471d-ba25-8a768fae6b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlCiclo_DDD_L_LBI1T0&quot;)</value>
      <webElementGuid>732c9c29-b588-4c2b-b255-40c9adc98773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xddlCiclo_DDD_L_LBI1T0']</value>
      <webElementGuid>3e1c28f0-0070-4a24-b1d4-ce0f4ee69903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xddlCiclo_DDD_L_LBT']/tbody/tr[2]/td</value>
      <webElementGuid>7136cf14-8d96-4837-8b3f-233520fa4ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 285- (202209)'])[1]/following::td[1]</value>
      <webElementGuid>21f7f9e0-403a-42e7-a536-87f647521f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo'])[1]/following::td[9]</value>
      <webElementGuid>4630635e-5510-427a-9123-6431ed662d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 283- (202207)'])[1]/preceding::td[1]</value>
      <webElementGuid>0d0ce7a8-658c-4827-9b01-48cd775a3ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 282- (202206)'])[1]/preceding::td[2]</value>
      <webElementGuid>a437c549-7127-4c13-87b0-4672782babba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ciclo 284- (202208)']/parent::*</value>
      <webElementGuid>831aeba2-960c-41f0-b0ba-43da053dd21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td</value>
      <webElementGuid>0aa50a8a-697c-4117-a38c-7a756f33f43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xddlCiclo_DDD_L_LBI1T0' and (text() = 'Ciclo 284- (202208)' or . = 'Ciclo 284- (202208)')]</value>
      <webElementGuid>5db7fd24-3240-489b-bae5-dfda40061521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
