<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Lote 1 (1)</name>
   <tag></tag>
   <elementGuidId>cf8fb09d-18a7-4a8f-8033-722d8d22b888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xrpnlLote_xddlLoteDesde_DDD_L_LBI0T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xrpnlLote_xddlLoteDesde_DDD_L_LBI0T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2be0d15b-e2f0-4735-aca9-13bf205fb061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Office2010Blue dxeListBoxItemHover_Office2010Blue dxeListBoxItemSelected_Office2010Blue</value>
      <webElementGuid>6a992b07-662c-40d3-88c2-0a87ec4e7848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xrpnlLote_xddlLoteDesde_DDD_L_LBI0T0</value>
      <webElementGuid>720c7cc0-89db-47dd-b09b-03071772a0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lote 1</value>
      <webElementGuid>ce0d6b3f-0727-4f6d-9e76-751b50c26b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xrpnlLote_xddlLoteDesde_DDD_L_LBI0T0&quot;)</value>
      <webElementGuid>ae1cec55-c172-4562-b399-1baae8b49b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xrpnlLote_xddlLoteDesde_DDD_L_LBI0T0']</value>
      <webElementGuid>f10883c3-5597-4fd3-8da5-0abca2c38b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xrpnlLote_xddlLoteDesde_DDD_L_LBT']/tbody/tr/td</value>
      <webElementGuid>959e131b-ac38-4f3c-a8cc-eac91d41c23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desde'])[1]/following::td[8]</value>
      <webElementGuid>712e16da-70b7-4f6e-a0a8-41c244ca7ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todos'])[1]/following::td[10]</value>
      <webElementGuid>87da2120-7d2d-4d98-939a-88c966381655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lote 2'])[1]/preceding::td[1]</value>
      <webElementGuid>23e7f71a-e189-488c-87e3-58b9ac1b9c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lote 3'])[1]/preceding::td[2]</value>
      <webElementGuid>69932f62-4b9a-41dc-98a8-b8d609099561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lote 1']/parent::*</value>
      <webElementGuid>36ddf367-e2d6-40bb-a970-01f4063657eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/div/div/div/div/table/tbody/tr/td/div/table[2]/tbody/tr/td</value>
      <webElementGuid>b99c894a-a0c9-4a2d-90cd-48ceee0fc6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xrpnlLote_xddlLoteDesde_DDD_L_LBI0T0' and (text() = 'Lote 1' or . = 'Lote 1')]</value>
      <webElementGuid>1ab428ae-9e29-4597-98f0-c1d971ba80f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
