<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Procesos (2)</name>
   <tag></tag>
   <elementGuidId>18eb4303-a50f-4d42-9cfd-fc000cf36e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ItemModulo_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ItemModulo_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a83a9ea-9675-4bb8-ac68-bd3ab490c7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ItemModulo_3</value>
      <webElementGuid>89713066-d96c-425c-8351-5e6c705cce33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cambioModulo(this,3,accesoModProcesos)</value>
      <webElementGuid>0cd43a85-a16f-4412-bc6c-13f0de4f4f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-modulo procesos</value>
      <webElementGuid>0ba05702-a7b5-4385-aa24-95d08494e716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Módulo de Procesos</value>
      <webElementGuid>193fdbc2-3068-4fa3-8e00-7f2a154b0808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procesos</value>
      <webElementGuid>fd29e04b-b61f-4557-b58c-c6677f39279a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ItemModulo_3&quot;)</value>
      <webElementGuid>15430e98-6d83-403e-94ec-f7b5e26de5f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ItemModulo_3']</value>
      <webElementGuid>02bebabc-b43f-4404-9424-ec07dc08209d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_div_modulos']/div[3]</value>
      <webElementGuid>adea9ba1-3e97-4a9a-9e5d-c879767b0788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::div[1]</value>
      <webElementGuid>ae2828b0-20d0-41df-b9c0-738a5c7f84e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención de Cliente'])[1]/following::div[2]</value>
      <webElementGuid>e51c0426-c6f5-4061-88c7-b65079a56b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operaciones'])[2]/preceding::div[1]</value>
      <webElementGuid>fde1ecab-9efc-4cfe-aced-d2ee964e03f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Procesos']/parent::*</value>
      <webElementGuid>8def883a-1e41-4d22-a594-c8f38956f521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[3]</value>
      <webElementGuid>f48b2cc3-d028-40b5-843f-0161ad1ef5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ItemModulo_3' and @title = 'Módulo de Procesos' and (text() = 'Procesos' or . = 'Procesos')]</value>
      <webElementGuid>b48613fa-37dd-4305-ba95-e552eecaa5da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
