<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Procesos</name>
   <tag></tag>
   <elementGuidId>f335d011-0624-4ac7-aaad-e2c832f08724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ItemModulo_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ItemModulo_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59eaeeb3-708c-43f1-be0b-15acd55ae9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ItemModulo_3</value>
      <webElementGuid>7bff699d-1d9e-416c-a345-5f4fd8765a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cambioModulo(this,3,accesoModProcesos)</value>
      <webElementGuid>11bc9af7-e26d-4c44-8677-4d024bbd2b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-modulo procesos</value>
      <webElementGuid>4d1aeac2-117f-4059-b154-2355f227d594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Módulo de Procesos</value>
      <webElementGuid>d523a70b-9bb4-4a21-b211-f6b86c899f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procesos</value>
      <webElementGuid>a31c4460-c6b8-4c2c-9eb3-729867c30874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ItemModulo_3&quot;)</value>
      <webElementGuid>c38e3474-c64c-44c4-ab72-660632e4b7c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ItemModulo_3']</value>
      <webElementGuid>05852d4c-c578-4dad-99c2-d9fca9d5beb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_div_modulos']/div[3]</value>
      <webElementGuid>2a246b0c-dcc0-4b56-828a-937214e5dd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::div[1]</value>
      <webElementGuid>c05069de-fc12-4138-90c2-f0dd97320b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención de Cliente'])[1]/following::div[2]</value>
      <webElementGuid>45e0db50-22db-4ceb-a1b5-552f165dbab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operaciones'])[1]/preceding::div[1]</value>
      <webElementGuid>402285b7-7aa4-4ed6-9e78-38b46a26677b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Procesos']/parent::*</value>
      <webElementGuid>dc1b1e07-fc1c-47c1-b273-52f48fa89866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[3]</value>
      <webElementGuid>50a751db-2c99-4359-9982-a52c3d77821a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ItemModulo_3' and @title = 'Módulo de Procesos' and (text() = 'Procesos' or . = 'Procesos')]</value>
      <webElementGuid>481ab08b-fd67-4c28-9b1d-60eccc4b88c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
