<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Procesos (1)</name>
   <tag></tag>
   <elementGuidId>747867d6-33e9-41de-8a9b-292d5cf06efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ItemModulo_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ItemModulo_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd7c9ffc-2424-4c4b-aa67-a606d89dc8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ItemModulo_3</value>
      <webElementGuid>68d5a995-a368-4b7d-b3e7-0e3c3c555dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cambioModulo(this,3,accesoModProcesos)</value>
      <webElementGuid>64a974eb-b050-46ec-941f-e8cba744d79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-modulo procesos</value>
      <webElementGuid>0b0b513a-3f18-4aae-b499-552bf0f2e85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Módulo de Procesos</value>
      <webElementGuid>3ce6f4c2-d76e-4fd7-a60e-6d472774e3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procesos</value>
      <webElementGuid>5e8b45aa-a690-4058-813f-545fb56ca17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ItemModulo_3&quot;)</value>
      <webElementGuid>5dc4793e-1a23-42c6-92ed-a12bf2c7a0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ItemModulo_3']</value>
      <webElementGuid>b5897f4e-1248-4758-b0e1-0f9f14b5bbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_div_modulos']/div[3]</value>
      <webElementGuid>05150fe8-1830-49b8-b4e2-53b75f451812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::div[1]</value>
      <webElementGuid>d5c33323-dea6-4937-af01-0d5653bbaa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención de Cliente'])[1]/following::div[2]</value>
      <webElementGuid>fc0b70ea-7aa8-4d03-8779-39fa408e9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operaciones'])[2]/preceding::div[1]</value>
      <webElementGuid>fb7291b5-fcf8-469a-9ca7-e0266ce5a690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Procesos']/parent::*</value>
      <webElementGuid>81cb473a-c59d-4505-8084-da276c4f4d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div[3]</value>
      <webElementGuid>daffd8a4-ffa0-4bff-8ad6-cb10bad62a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_ItemModulo_3' and @title = 'Módulo de Procesos' and (text() = 'Procesos' or . = 'Procesos')]</value>
      <webElementGuid>742b0b18-583e-4449-8d98-967d582d366b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
