<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_-_xbtnBuscarClienteImg</name>
   <tag></tag>
   <elementGuidId>ae4107ea-af3a-4dec-9887-4ba5485ae372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xbtnBuscarClienteImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xbtnBuscarClienteImg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d0e1bf6a-b35e-4ed7-84c5-473dda098d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-vam</value>
      <webElementGuid>ce6a20c6-0679-44ff-b2ca-7bd77dd057a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/Images/buscar1.png</value>
      <webElementGuid>7466f244-0f85-4634-965f-5f7df5d5e4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xbtnBuscarClienteImg</value>
      <webElementGuid>50980de4-a365-42e8-8920-6e08fccf123e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xbtnBuscarClienteImg&quot;)</value>
      <webElementGuid>b68d632d-4b31-499a-8ecc-b9fa81b5ce2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xbtnBuscarClienteImg']</value>
      <webElementGuid>fdd7519b-7fb0-43e3-ac16-4f095826d002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xbtnBuscarCliente_CD']/img</value>
      <webElementGuid>c88ffce1-9027-4eff-b1b5-954b55567772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6b71db6e-6f98-4db3-a9e5-cae4a753f727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'Recursos/Images/buscar1.png' and @id = 'xbtnBuscarClienteImg']</value>
      <webElementGuid>194ae2c3-b196-4e72-9d8b-2cb72d6903f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
