<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Direccin_ASPxRoundPanel1xtxtDirecion</name>
   <tag></tag>
   <elementGuidId>080339a2-99d9-4fec-90ab-05c9fe546531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ASPxRoundPanel1_xtxtDirecion_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ASPxRoundPanel1_xtxtDirecion_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8d856b1-b630-4acd-924d-687d6e9678df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>10c8b577-2ac6-4e13-a74f-92e5b77711ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ASPxRoundPanel1_xtxtDirecion_I</value>
      <webElementGuid>85255e26-186f-4ad5-b506-b0628a8c8079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ASPxRoundPanel1$xtxtDirecion</value>
      <webElementGuid>4c7b46fa-9d4f-4158-b339-f39cc54d74b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e7039a88-6bc4-458f-9164-5522e3c213d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ASPxRoundPanel1_xtxtDirecion')</value>
      <webElementGuid>15122645-24c7-4eab-9600-40e34e9a0068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ASPxRoundPanel1_xtxtDirecion')</value>
      <webElementGuid>6cdb33fc-a36a-48ee-a666-325e517b6979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('ASPxRoundPanel1_xtxtDirecion')</value>
      <webElementGuid>2035215e-ebcc-461d-8acb-0807162971a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5596634e-7dca-47c1-bb1e-eba6b04e2716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ASPxRoundPanel1_xtxtDirecion_I&quot;)</value>
      <webElementGuid>364b2df4-e645-4dfe-9f72-64a62bb54d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ASPxRoundPanel1_xtxtDirecion_I']</value>
      <webElementGuid>f38f4abb-0e52-4793-bdf2-cb581482f32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ASPxRoundPanel1_xtxtDirecion']/tbody/tr/td/input</value>
      <webElementGuid>1f11483d-26a8-4a79-8d4b-f89b899cdc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>316e7e5b-1e9c-43c5-88a6-d3eeaba7be02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ASPxRoundPanel1_xtxtDirecion_I' and @name = 'ASPxRoundPanel1$xtxtDirecion' and @type = 'text']</value>
      <webElementGuid>f895f2f6-8fbb-4aed-b647-5d2bdbcebc06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
