<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N Servicio_xtxtIdServicio</name>
   <tag></tag>
   <elementGuidId>9d0f1532-7099-4d8f-a68a-ed3efe4a8d2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xtxtIdServicio_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xtxtIdServicio_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d6a85e6-e8ad-4f32-b904-068814997818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>b2e2911d-65d6-4779-9198-043762a0010f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xtxtIdServicio_I</value>
      <webElementGuid>eb2b7513-239e-4764-800b-a5ac2fbc2d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xtxtIdServicio</value>
      <webElementGuid>60a69405-f72a-41fe-a2f7-f22632889fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('xtxtIdServicio')</value>
      <webElementGuid>dd5bf14c-c256-4e9d-a745-ef5e8860564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('xtxtIdServicio')</value>
      <webElementGuid>020120d4-21f2-417f-a0fc-c1cddc8cf718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('xtxtIdServicio')</value>
      <webElementGuid>a72a0e83-04c7-4265-8a41-e9f632a2978e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b0360ed-b199-42a5-8d2b-86afc8e7edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1d649a95-f9ee-4195-a23f-ca6276a4a8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xtxtIdServicio_I&quot;)</value>
      <webElementGuid>e212fbb7-95ff-4e67-b6d5-d78ddf89c40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xtxtIdServicio_I']</value>
      <webElementGuid>db67831d-01f3-44a1-96f1-d61939bfedf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xtxtIdServicio']/tbody/tr/td/input</value>
      <webElementGuid>f6b33823-8f02-4626-bd56-45e7afef5dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>28fb8f3e-8c0b-419f-ada3-85b4ecbbf401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xtxtIdServicio_I' and @name = 'xtxtIdServicio' and @type = 'text']</value>
      <webElementGuid>2779f6ab-0d82-425f-8a85-630696d261bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
