<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombres_ASPxRoundPanel1xtxtCliente</name>
   <tag></tag>
   <elementGuidId>99104cd6-539d-45aa-ad38-878ff5b3816e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ASPxRoundPanel1_xtxtCliente_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ASPxRoundPanel1_xtxtCliente_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7194cd7c-2a4b-4d71-ae1d-1b4c45c8c3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>11b43af1-6b26-4c8b-86d9-b55416954e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ASPxRoundPanel1_xtxtCliente_I</value>
      <webElementGuid>60884f40-5ffd-47d3-8cc2-69e444e6ace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ASPxRoundPanel1$xtxtCliente</value>
      <webElementGuid>9dff83c9-d699-422e-953b-e740ae5928d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>f4d839dc-2084-4676-bc63-11d47edd8e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ASPxRoundPanel1_xtxtCliente')</value>
      <webElementGuid>11a7e482-91fa-4376-9df9-dfa1f5abebb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ASPxRoundPanel1_xtxtCliente')</value>
      <webElementGuid>414ad8a4-2cac-4708-8d30-30cde42518cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('ASPxRoundPanel1_xtxtCliente')</value>
      <webElementGuid>ee1d02bb-a4e6-4882-8a41-99471f6a690b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47b2f542-f5b4-4e56-8859-32ffe8290fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ASPxRoundPanel1_xtxtCliente_I&quot;)</value>
      <webElementGuid>b88158e2-1400-461d-9894-885b16fe4608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ASPxRoundPanel1_xtxtCliente_I']</value>
      <webElementGuid>2842c15f-264d-4da6-b2a4-44bd75d63bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ASPxRoundPanel1_xtxtCliente']/tbody/tr/td/input</value>
      <webElementGuid>48b4cc99-a3fb-4ca1-baa5-40e4a1620468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>728255dc-3a24-4cf1-85af-774ef10a7b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ASPxRoundPanel1_xtxtCliente_I' and @name = 'ASPxRoundPanel1$xtxtCliente' and @type = 'text']</value>
      <webElementGuid>dd2a7509-af76-4f1f-803e-39282c94670c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
