<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Transparente_showLegend-image</name>
   <tag></tag>
   <elementGuidId>1d1a0b09-ec4a-40e1-81dd-eaa586a0f2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='uniqName_14_0']/tbody/tr[7]/td/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.jimu-widget-row.layer-row.layer-row-mouseover > td.col.col1 > div.showLegend-div.jimu-float-leading > img.showLegend-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showLegend-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/giswebvisor/widgets/LayerList/images/v_right.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>l</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqName_14_0&quot;)/tbody[@class=&quot;layers-list-body&quot;]/tr[@class=&quot;jimu-widget-row layer-row layer-row-mouseover&quot;]/td[@class=&quot;col col1&quot;]/div[@class=&quot;showLegend-div jimu-float-leading&quot;]/img[@class=&quot;showLegend-image&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_GIS Web - Aguas Nuevas/iframe_concat(id(, , frame1, , ))_frame1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uniqName_14_0']/tbody/tr[7]/td/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='l'])[145]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/div/img</value>
   </webElementXpaths>
</WebElementEntity>
