<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HISTORIAL DE RDENES</name>
   <tag></tag>
   <elementGuidId>332e1fcd-39f4-4d8f-bd0e-c1ae4ec446c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Arbol_Menut36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Arbol_Menut36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>954d8d3f-858d-4849-b40d-0874df3313e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Arbol_Menu_0</value>
      <webElementGuid>5479b1e9-8e50-4dbf-a1f1-d6ec83b715ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>GestionCortes.aspx</value>
      <webElementGuid>6a3dd963-0584-4d20-a665-41242ad54680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>5641c308-5a22-451d-8270-dca344630e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:TreeView_SelectNode(Arbol_Menu_Data, this,'Arbol_Menut36');</value>
      <webElementGuid>47153d0e-8f56-40af-a073-3325c57f66ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Arbol_Menut36</value>
      <webElementGuid>7b68ee9c-9653-4da4-80b8-2c550a0c4191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HISTORIAL DE ÓRDENES</value>
      <webElementGuid>9da34150-c23c-4702-a14b-ec421465d248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Arbol_Menut36&quot;)</value>
      <webElementGuid>0b9c12e0-583f-4bc8-b09a-c063f83b9e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Arbol_Menut36']</value>
      <webElementGuid>71502a25-1274-49bf-9738-f6688db33af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Arbol_Menun34Nodes']/table[2]/tbody/tr/td[5]/a</value>
      <webElementGuid>169ce1a9-d5f1-4dd1-ac6e-2918339fd3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HISTORIAL DE ÓRDENES')]</value>
      <webElementGuid>5f3c486a-aa4e-4cc6-8b4a-b2fcc6c33e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VISOR FOTOGRAFÍA'])[1]/following::a[2]</value>
      <webElementGuid>64a4142d-bc3e-433a-b27d-76c041fe8fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GESTIÓN DE REPORTES'])[1]/following::a[4]</value>
      <webElementGuid>30573aa8-ef4b-48d7-83ec-14f17ddd485e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESPALDO FOTOGRAFICO'])[1]/preceding::a[2]</value>
      <webElementGuid>326c9ec3-67e1-449c-b359-6259d826d4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAPA GIS'])[1]/preceding::a[4]</value>
      <webElementGuid>d3d809fc-7d07-4984-8e8d-aeabb0e8db75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HISTORIAL DE ÓRDENES']/parent::*</value>
      <webElementGuid>877f2b87-d93a-4991-9d34-2bcf317fbd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'GestionCortes.aspx')])[2]</value>
      <webElementGuid>f0af3d32-9425-4ac6-bb6c-28b513447de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table[2]/tbody/tr/td[5]/a</value>
      <webElementGuid>d88aecbb-67cf-4b05-94b7-149fd308857f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'GestionCortes.aspx' and @id = 'Arbol_Menut36' and (text() = 'HISTORIAL DE ÓRDENES' or . = 'HISTORIAL DE ÓRDENES')]</value>
      <webElementGuid>2c112a0d-ad32-47e5-b547-045f9c713716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
