<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ANAISABELPUGACONTRERAS</name>
   <tag></tag>
   <elementGuidId>20159f4c-08c9-4b5f-a059-3e2d40810636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report_div']/div/table/tbody/tr[17]/td[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fc87a53b-236e-445b-bab2-4f36323fe37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cs36FF8CA3</value>
      <webElementGuid>3d5edb75-82bf-4460-8bb5-749cbcdaa4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e4242ac6-cc85-4d30-a859-612aee1ab9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ANA ISABEL PUGA CONTRERAS</value>
      <webElementGuid>d1af93c9-9822-4735-ad4e-79449ac08e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_div&quot;)/div[@class=&quot;page-background-color-holder&quot;]/table[1]/tbody[1]/tr[17]/td[@class=&quot;cs36FF8CA3&quot;]</value>
      <webElementGuid>6f093452-c305-4aa1-a11e-755b9d806829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Listado de servicios con sobreconsumo123/iframe_Cargando_xdocView_Splitter_Viewer_ContentFrame</value>
      <webElementGuid>6b138b3f-ef6f-4637-ac31-aed127d709f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report_div']/div/table/tbody/tr[17]/td[5]</value>
      <webElementGuid>ecc4cdb8-8548-4035-84ff-276ec36ddcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sector 1'])[1]/following::td[29]</value>
      <webElementGuid>2cf5e074-4bce-43f5-afff-d7c6679e13f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sector:'])[1]/following::td[32]</value>
      <webElementGuid>315f8078-0e59-4359-84e8-7454a01ec082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M LEMEUR FTE TENENCI 36'])[1]/preceding::td[1]</value>
      <webElementGuid>855d48b4-9fbf-4c6c-ad85-adce1be117ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[5]</value>
      <webElementGuid>a3d49439-0e4e-4660-897a-97d8f4acec78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ANA ISABEL PUGA CONTRERAS' or . = 'ANA ISABEL PUGA CONTRERAS')]</value>
      <webElementGuid>9619b6e7-29a7-458a-9ba5-c2a70fcd1128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
