<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cargando_xdocView_Splitter_Viewer_Co_be9726</name>
   <tag></tag>
   <elementGuidId>ceb2872f-9626-4a53-beca-999b2c5ea5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='xdocView_Splitter_Viewer_ContentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xdocView_Splitter_Viewer_ContentFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7611623f-7dd7-4542-ad69-0c4732af87fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xdocView_Splitter_Viewer_ContentFrame</value>
      <webElementGuid>f9696bd4-7e74-47ff-ad67-34aebf04b6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xdocView_Splitter_Viewer_ContentFrame</value>
      <webElementGuid>b95a4bf1-9d1a-47b2-af29-4f72021e58b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>05b3a8ba-1d8f-4dfd-acc3-28e2f80d57f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdocView_Splitter_Viewer_ContentFrame&quot;)</value>
      <webElementGuid>c3bbddf1-98b0-4dc6-867c-722bb75f9046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='xdocView_Splitter_Viewer_ContentFrame']</value>
      <webElementGuid>d705cfd8-94aa-4575-b30c-a3b0a1e9006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdocView_Splitter_Viewer_Div']/iframe</value>
      <webElementGuid>fa3f3fa6-abf3-4a3d-b961-6bb43a234d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>12bd4343-529f-4f66-876e-77f679e0d980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'xdocView_Splitter_Viewer_ContentFrame' and @name = 'xdocView_Splitter_Viewer_ContentFrame']</value>
      <webElementGuid>f406d287-c8e2-4310-afab-58b8ca8cc68f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
