<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cargando_xdocView_Splitter_Toolbar_Menu_8b5a71</name>
   <tag></tag>
   <elementGuidId>9e1835e2-3812-4c51-931f-ca0394b409f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xdocView_Splitter_Toolbar_Menu_DXI13_Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xdocView_Splitter_Toolbar_Menu_DXI13_Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>83dd14e9-1a8e-49cc-8711-82c9b7865fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Excel sin formato</value>
      <webElementGuid>7ceaf124-2c7b-4095-b937-10e336363cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxm-image dx-vam</value>
      <webElementGuid>5cac3829-fc63-403b-8688-57d58db9630e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Recursos/images/page_excel.gif</value>
      <webElementGuid>ecf3fda4-066c-4b91-8858-d90c95ab162e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Excel sin formato</value>
      <webElementGuid>365145a6-8eca-410d-b937-4a2442d765e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xdocView_Splitter_Toolbar_Menu_DXI13_Img</value>
      <webElementGuid>6c02733f-2b84-4052-9d46-b9f6eb4fb0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdocView_Splitter_Toolbar_Menu_DXI13_Img&quot;)</value>
      <webElementGuid>39cedf25-c450-40f7-8eff-410edfbd01a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xdocView_Splitter_Toolbar_Menu_DXI13_Img']</value>
      <webElementGuid>49bc618f-8a56-46f8-8acb-a2f61b80405d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdocView_Splitter_Toolbar_Menu_DXI13_T']/img</value>
      <webElementGuid>b6d3c161-95fe-4a13-a1d9-3311ec0674a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Excel sin formato']</value>
      <webElementGuid>034d7ddc-494e-4424-99d8-3e2b751a1f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[27]/div/img</value>
      <webElementGuid>7deb377f-7be6-423e-a338-f48dd048e8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Excel sin formato' and @src = 'Recursos/images/page_excel.gif' and @alt = 'Excel sin formato' and @id = 'xdocView_Splitter_Toolbar_Menu_DXI13_Img']</value>
      <webElementGuid>0ee9efe8-8b27-4d19-bfef-fe725fa8cda5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
