<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ciclo_xrpnlLote_xddlCiclo_B-1Img</name>
   <tag></tag>
   <elementGuidId>93a1b5c1-07f1-46b6-9a5d-a1d1ecbc3c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xrpnlLote_xddlCiclo_B-1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xrpnlLote_xddlCiclo_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7f2bafa-e028-4cba-9196-534b2de63f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xrpnlLote_xddlCiclo_B-1Img</value>
      <webElementGuid>706f2d79-6347-4219-a0cf-cc4d0b23fab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Office2010Blue</value>
      <webElementGuid>24b5195b-a633-4eed-9bee-e2395e62d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_19-zQ8Pb</value>
      <webElementGuid>cae87eec-a7b3-41e3-8211-b49b9095aa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>e198a3cf-b548-45bd-8be6-6e42742c6b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xrpnlLote_xddlCiclo_B-1Img&quot;)</value>
      <webElementGuid>ffe454e2-fb6d-45fa-9d6a-9cfb32002cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xrpnlLote_xddlCiclo_B-1Img']</value>
      <webElementGuid>65ed0e77-277e-42ce-aa47-1868f1afacbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='xrpnlLote_xddlCiclo_B-1']/img</value>
      <webElementGuid>fa15449e-ae3f-48ec-a946-71c8beb53e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>73f18d72-9e28-4abd-bdf2-12b770e118df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fbe3439b-5528-411d-8776-404db78c8dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'xrpnlLote_xddlCiclo_B-1Img' and @src = '/DXR.axd?r=1_19-zQ8Pb' and @alt = 'v']</value>
      <webElementGuid>7ca91d71-6e02-4d3f-ba8a-2ce868acd1c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
