<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hasta_ASPxRoundPanel2xtxtNoDocumentoHasta</name>
   <tag></tag>
   <elementGuidId>4d942f34-1f38-48d5-85d3-bd360336f9ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ASPxRoundPanel2_xtxtNoDocumentoHasta_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ASPxRoundPanel2_xtxtNoDocumentoHasta_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e41a5f20-be0f-41f6-9d89-7327004fe774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>b6cd0995-a7d8-4913-bc69-050dd6138092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ASPxRoundPanel2_xtxtNoDocumentoHasta_I</value>
      <webElementGuid>94fc8938-349c-4d5d-b9af-b9298ce10a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ASPxRoundPanel2$xtxtNoDocumentoHasta</value>
      <webElementGuid>d5e05746-e648-424f-817d-5cc140e72cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ASPxRoundPanel2_xtxtNoDocumentoHasta')</value>
      <webElementGuid>106aa1ca-6310-495e-878a-56da5b420e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ASPxRoundPanel2_xtxtNoDocumentoHasta')</value>
      <webElementGuid>40448a34-6756-4c2a-b1c2-a8e8a252d065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('ASPxRoundPanel2_xtxtNoDocumentoHasta')</value>
      <webElementGuid>d5c098a7-8ea0-40c3-8827-e0aa4c49f955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0e135280-1c16-41a1-9dd6-7e1143d448bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>939c9311-432a-49b8-9e37-77162dbcc003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ASPxRoundPanel2_xtxtNoDocumentoHasta_I&quot;)</value>
      <webElementGuid>1e57b9e7-376b-4a4c-be9c-7f0adca9d114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ASPxRoundPanel2_xtxtNoDocumentoHasta_I']</value>
      <webElementGuid>4ee02857-9ef0-4154-877a-0c541b7bfbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ASPxRoundPanel2_xtxtNoDocumentoHasta']/tbody/tr/td/input</value>
      <webElementGuid>36a8aa99-5044-425a-89bc-50e2d026ae8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>b195b144-1446-4945-a905-cca9989cf0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ASPxRoundPanel2_xtxtNoDocumentoHasta_I' and @name = 'ASPxRoundPanel2$xtxtNoDocumentoHasta' and @type = 'text']</value>
      <webElementGuid>07dd3d5f-4325-4bfb-987a-3a90434a85f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
