<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Desde_ASPxRoundPanel2xtxtNoDocumentoDesde</name>
   <tag></tag>
   <elementGuidId>f6d3f9d2-b259-4e41-b291-bd40c5975cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ASPxRoundPanel2_xtxtNoDocumentoDesde_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ASPxRoundPanel2_xtxtNoDocumentoDesde_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>285d3bbf-83ab-4658-93f5-c728daff7459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>5d49e750-644c-49c0-8668-82ae7fe3c9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ASPxRoundPanel2_xtxtNoDocumentoDesde_I</value>
      <webElementGuid>6d95d60b-3cff-4307-ace7-ff7dc2c5286a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ASPxRoundPanel2$xtxtNoDocumentoDesde</value>
      <webElementGuid>8b37c903-208b-474f-a1d3-2cfd3401fdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('ASPxRoundPanel2_xtxtNoDocumentoDesde')</value>
      <webElementGuid>e5720768-c2ca-4f67-8006-0a03a11a20dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('ASPxRoundPanel2_xtxtNoDocumentoDesde')</value>
      <webElementGuid>2f50a8dc-3953-4d87-a90d-25b106cd8a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('ASPxRoundPanel2_xtxtNoDocumentoDesde')</value>
      <webElementGuid>1c29c7ce-5c04-481c-b8b4-f834e4bc8247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38ac93d0-057c-46e8-a76c-23ecf16c9434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0474106-7203-4200-94ca-afa47743d759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ASPxRoundPanel2_xtxtNoDocumentoDesde_I&quot;)</value>
      <webElementGuid>32df7d98-d65f-4c15-ab82-235e009274cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ASPxRoundPanel2_xtxtNoDocumentoDesde_I']</value>
      <webElementGuid>16cc6bd5-2ee7-4c06-8a75-5ea33131f7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ASPxRoundPanel2_xtxtNoDocumentoDesde']/tbody/tr/td/input</value>
      <webElementGuid>0c2a4e37-2880-45a5-abae-8687e7e89797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/table/tbody/tr[2]/td[3]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>4310cff6-4c4d-4bd3-be07-026afc433eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ASPxRoundPanel2_xtxtNoDocumentoDesde_I' and @name = 'ASPxRoundPanel2$xtxtNoDocumentoDesde' and @type = 'text']</value>
      <webElementGuid>a32cdd56-8d8b-446f-95db-80d3ac7cadeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
