<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Ciclo 345- (202208)</name>
   <tag></tag>
   <elementGuidId>5cc348f5-9f28-4265-b21a-7c6c4433f136</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xrpnlLote_xddlCiclo_DDD_L_LBI1T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xrpnlLote_xddlCiclo_DDD_L_LBI1T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d0bc6609-58ac-4c4b-a852-e8abc4279332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Office2010Blue dxeListBoxItemHover_Office2010Blue dxeListBoxItemSelected_Office2010Blue</value>
      <webElementGuid>0f4c37cc-40a1-4257-bad0-062370804617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xrpnlLote_xddlCiclo_DDD_L_LBI1T0</value>
      <webElementGuid>a484086d-09bc-4f5b-89ca-f6a41c02a13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ciclo 345- (202208)</value>
      <webElementGuid>53a3363b-85c2-4c9d-a9c7-d8b61c3cb04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xrpnlLote_xddlCiclo_DDD_L_LBI1T0&quot;)</value>
      <webElementGuid>c9427a25-06c0-4fbc-919a-f8cc21ed469e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xrpnlLote_xddlCiclo_DDD_L_LBI1T0']</value>
      <webElementGuid>96112f93-d03a-4367-8789-af9c1041615d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xrpnlLote_xddlCiclo_DDD_L_LBT']/tbody/tr[2]/td</value>
      <webElementGuid>e58d2ec2-0144-440c-8733-8da67a22968e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 346- (202209)'])[1]/following::td[1]</value>
      <webElementGuid>cb7d8e19-9b1f-479e-9a96-55831e42cdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo'])[1]/following::td[9]</value>
      <webElementGuid>545ca86e-4735-46ce-a67d-a18e1c905725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 344- (202207)'])[1]/preceding::td[1]</value>
      <webElementGuid>d5aea9b1-249f-4131-84d5-919698ce6bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 343- (202206)'])[1]/preceding::td[2]</value>
      <webElementGuid>ba76b807-1e48-4da5-9fcc-50a9f69a461b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ciclo 345- (202208)']/parent::*</value>
      <webElementGuid>43245ca2-03c5-451e-a358-84257781152e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td</value>
      <webElementGuid>453f12b5-f187-4449-83eb-d700d90428b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xrpnlLote_xddlCiclo_DDD_L_LBI1T0' and (text() = 'Ciclo 345- (202208)' or . = 'Ciclo 345- (202208)')]</value>
      <webElementGuid>569aef82-88ec-474e-82e4-356f5bacc38b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
