<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Ciclo 288- (202208)</name>
   <tag></tag>
   <elementGuidId>cfc42931-e189-4ec8-b1ba-76ac81f678e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xrpnlLote_xddlCiclo_DDD_L_LBI1T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xrpnlLote_xddlCiclo_DDD_L_LBI1T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f208bc98-a130-4b50-a40d-1548ce0b8321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Office2010Blue dxeListBoxItemHover_Office2010Blue dxeListBoxItemSelected_Office2010Blue</value>
      <webElementGuid>cf64b56e-43ab-4334-b9a2-29c154672928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xrpnlLote_xddlCiclo_DDD_L_LBI1T0</value>
      <webElementGuid>a1be03ea-3c57-41e2-bd00-076cff199602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ciclo 288- (202208)</value>
      <webElementGuid>ddc0af3a-6f67-447c-b895-acca03726d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xrpnlLote_xddlCiclo_DDD_L_LBI1T0&quot;)</value>
      <webElementGuid>0f568f2b-009d-433b-a8bf-29d189784e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xrpnlLote_xddlCiclo_DDD_L_LBI1T0']</value>
      <webElementGuid>7e071bb6-24aa-4932-b645-2c435fcfa1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xrpnlLote_xddlCiclo_DDD_L_LBT']/tbody/tr[2]/td</value>
      <webElementGuid>224e9438-5426-40c9-b987-1bbe8d738a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 289- (202209)'])[1]/following::td[1]</value>
      <webElementGuid>3d271998-0ea8-4e13-ae37-4c292342328d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo'])[1]/following::td[9]</value>
      <webElementGuid>45b3b8cf-9b78-4468-8955-28a171d0b541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 287- (202207)'])[1]/preceding::td[1]</value>
      <webElementGuid>e6f8e380-a185-4a02-ae9d-6a5aa14f3347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciclo 286- (202206)'])[1]/preceding::td[2]</value>
      <webElementGuid>d47dfaa3-e1f0-4d32-8639-2f119d5a760d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ciclo 288- (202208)']/parent::*</value>
      <webElementGuid>b4d6e253-cd0e-4b1b-a15b-a500fbed4f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td</value>
      <webElementGuid>bae1ab77-3230-4e50-a324-4c11e5446a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xrpnlLote_xddlCiclo_DDD_L_LBI1T0' and (text() = 'Ciclo 288- (202208)' or . = 'Ciclo 288- (202208)')]</value>
      <webElementGuid>1c21ad34-8e64-4c53-baa1-b5ede565cd06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
