<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Empresa_xddlEmpresa_B-1Img (2)</name>
   <tag></tag>
   <elementGuidId>591370a1-3ba7-4871-979c-c2820e40c9b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xddlEmpresa_B-1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlEmpresa_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3dd4b26-02af-490f-b6c8-c3a10ff24f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlEmpresa_B-1Img</value>
      <webElementGuid>04994004-c1ac-461b-b5ff-c173a6069b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Office2010Blue</value>
      <webElementGuid>ae6b2c16-cdb1-4685-8ac9-b8b0570ca6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_19-zQ8Pb</value>
      <webElementGuid>b756f83b-7b4d-4e92-bf75-9711ba0d446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>b750974c-fdf6-46e1-9cb7-130d39833490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlEmpresa_B-1Img&quot;)</value>
      <webElementGuid>5d512f00-5fca-4e8e-9d38-7eccc281c8f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xddlEmpresa_B-1Img']</value>
      <webElementGuid>2484f7ef-5887-45d6-804e-31cd5a5cc418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='xddlEmpresa_B-1']/img</value>
      <webElementGuid>d1fb661d-8c15-480f-bdfc-59301da65e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>bf464318-5240-4599-9263-93b6bf28cf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/img</value>
      <webElementGuid>df005108-5d7c-4ddf-b471-f3ea3c4889d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'xddlEmpresa_B-1Img' and @src = '/DXR.axd?r=1_19-zQ8Pb' and @alt = 'v']</value>
      <webElementGuid>5f102fc2-7dcc-4668-bb17-71e22cf1885d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
