<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Empresa_xddlEmpresa_B-1Img (1)</name>
   <tag></tag>
   <elementGuidId>186f4631-a2be-43be-a5d0-cb20b87a611f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xddlEmpresa_B-1Img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlEmpresa_B-1Img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a66d395a-1cdc-46d3-a3f9-90fccb4dd364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlEmpresa_B-1Img</value>
      <webElementGuid>787c65eb-d371-40f9-a194-cdb33a9a0353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_Office2010Blue</value>
      <webElementGuid>a80d9455-30a3-48c2-b14e-39b1b42a20a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DXR.axd?r=1_19-zQ8Pb</value>
      <webElementGuid>dd2d9cd8-10b5-4937-b655-19ae9891d44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>30df1d29-2110-47d9-b4df-09bc84efac7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlEmpresa_B-1Img&quot;)</value>
      <webElementGuid>074f6296-646c-4a24-922e-c212a7ffcbed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xddlEmpresa_B-1Img']</value>
      <webElementGuid>4c3e4703-7ba4-4788-b023-6a64c9e23308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='xddlEmpresa_B-1']/img</value>
      <webElementGuid>367606aa-980d-441a-bf14-58e71adb04f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>c10e5af8-3655-41ab-bda3-99294899391d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/img</value>
      <webElementGuid>d79a9d50-6aa0-40c2-91d0-7360ed86aac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'xddlEmpresa_B-1Img' and @src = '/DXR.axd?r=1_19-zQ8Pb' and @alt = 'v']</value>
      <webElementGuid>22a67607-d453-4197-ade5-1034c1b8ca77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
