<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario_txtxUsuario (2)</name>
   <tag></tag>
   <elementGuidId>d6c1882d-5533-4242-952d-ba6c84f42bbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtxUsuario_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtxUsuario_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28c9159c-3a2a-4152-a297-26aa5fa5099f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>4ce3e133-3e49-4a26-ba67-a7eb43d23dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtxUsuario_I</value>
      <webElementGuid>acc67c0b-a08e-437e-8bee-069ef5faf14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtxUsuario</value>
      <webElementGuid>b6ff7ff0-eaeb-41f5-aa28-3ed8c50f4fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('txtxUsuario')</value>
      <webElementGuid>5cc10a11-966c-4d4a-bdc2-6a93b02c35db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('txtxUsuario')</value>
      <webElementGuid>40833787-57dd-45ac-b0be-33eb75b28071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('txtxUsuario')</value>
      <webElementGuid>d026b010-6ac7-4385-ba6f-674b3c764d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d9e304c-9c5d-4d8f-9d8a-0f1fac400834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtxUsuario_I&quot;)</value>
      <webElementGuid>6a42a667-56f7-438d-995e-d089857dde74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtxUsuario_I']</value>
      <webElementGuid>9735a723-cef9-443c-ad5c-a29af8558a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='txtxUsuario']/tbody/tr/td/input</value>
      <webElementGuid>179c0bb0-5eab-444d-9796-c29102244bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>2d61ba84-a733-4861-a558-3fcf1cc983c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtxUsuario_I' and @name = 'txtxUsuario' and @type = 'text']</value>
      <webElementGuid>3bb2534d-4d1b-4494-81a7-7a74796f6131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
