<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario_txtxUsuario</name>
   <tag></tag>
   <elementGuidId>cd8cb287-5cb0-492e-acea-befdf557524a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtxUsuario_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtxUsuario_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2daf15e1-44f5-40da-a303-aacf6f22c364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>73268d89-6e50-4f07-a90d-03b487ec9e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtxUsuario_I</value>
      <webElementGuid>9d0f4c66-269e-49a0-a790-ee7370692dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtxUsuario</value>
      <webElementGuid>c7d69406-acde-45d7-8660-2bbb2c9817ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('txtxUsuario')</value>
      <webElementGuid>b0eccc83-f696-43f8-a09f-a2eb6fd7f0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('txtxUsuario')</value>
      <webElementGuid>b53f76ac-8c6a-415c-bb09-6ca1ba1e103b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('txtxUsuario')</value>
      <webElementGuid>4f930416-2e65-4f6f-9a87-78dbd943f537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4139b067-8ceb-4803-a3fd-6920f2cda459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtxUsuario_I&quot;)</value>
      <webElementGuid>e040771b-8b8c-48d4-9dac-9275356b3ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtxUsuario_I']</value>
      <webElementGuid>d4be00b9-768e-4aae-9ef0-0d9b16ca6fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='txtxUsuario']/tbody/tr/td/input</value>
      <webElementGuid>b3900381-3a71-4d9a-8662-c64e4523e1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>a47ab033-1a9a-438c-b1b2-59928c77dc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtxUsuario_I' and @name = 'txtxUsuario' and @type = 'text']</value>
      <webElementGuid>dbc7c83b-58ed-4cec-bff3-c85744f90dba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
