<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usuario_txtxUsuario (1)</name>
   <tag></tag>
   <elementGuidId>e5ef9ff9-a8ea-4f99-866a-b5b6d1a4cdf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtxUsuario_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtxUsuario_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4648007a-19e2-45ca-9be4-76d8981294cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>ae24293c-9310-4f0c-a189-f653eb38fc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtxUsuario_I</value>
      <webElementGuid>932bee8c-4c64-49c3-a852-48afa9b7da75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtxUsuario</value>
      <webElementGuid>00793072-5d13-4360-93eb-4c6ecfec0b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('txtxUsuario')</value>
      <webElementGuid>880f9def-73ea-4b11-83d5-d3f5291ef9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('txtxUsuario')</value>
      <webElementGuid>3a75c3f4-7cc9-407c-a414-b49bcb00cb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('txtxUsuario')</value>
      <webElementGuid>3130744a-12d2-4a07-9271-c3ddde7f998d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcc7cb94-45a6-4f5f-b281-a12ac7e0f73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtxUsuario_I&quot;)</value>
      <webElementGuid>7e0866a5-a65f-4f55-bbc3-076bd99aaa0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtxUsuario_I']</value>
      <webElementGuid>209055b8-441b-4308-96cc-ec3ec3b597ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='txtxUsuario']/tbody/tr/td/input</value>
      <webElementGuid>e6f7b5d2-d484-4608-935b-cd5d6c2d5830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>1435d9da-81e8-4456-a44c-27a9fb1f2ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtxUsuario_I' and @name = 'txtxUsuario' and @type = 'text']</value>
      <webElementGuid>5ad9efb4-d2a9-4299-95ad-c082e26c050c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
