<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_txtxContrasena (2)</name>
   <tag></tag>
   <elementGuidId>3ec3db2f-7f72-40b8-ad92-e66556146648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtxContrasena_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtxContrasena_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbd38a9a-dcca-4679-a8c6-28ca108595de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>31771859-4b3e-4d08-8fd8-c7acac9a66dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtxContrasena_I</value>
      <webElementGuid>f338ea66-b487-4e6f-90b7-6e82728fd849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtxContrasena</value>
      <webElementGuid>1d49f113-552f-42be-8a30-6c5f418383f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('txtxContrasena')</value>
      <webElementGuid>b8fa1155-eb0f-4981-b50a-d631f13e143f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('txtxContrasena')</value>
      <webElementGuid>b3a26a11-5c1a-494b-be2f-8e613d75b585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('txtxContrasena')</value>
      <webElementGuid>81a9e52c-fd2b-4795-8db1-eabf707805f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f9699004-8c55-4d63-bf88-2ade5e39476a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtxContrasena_I&quot;)</value>
      <webElementGuid>5c0c418d-f125-4b8a-ad68-f996e205445d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtxContrasena_I']</value>
      <webElementGuid>e83e2ea7-ff10-41ff-86c4-506bead1ae25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='txtxContrasena']/tbody/tr/td/input</value>
      <webElementGuid>6d32b970-5c8d-4b27-8f4b-be8a6adb3692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>4ab9c4c9-c6c6-4a21-a118-1edd71e8d6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtxContrasena_I' and @name = 'txtxContrasena' and @type = 'password']</value>
      <webElementGuid>6b0ec4b5-5676-4126-8245-43c4dcb708c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
