<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_txtxContrasena (1)</name>
   <tag></tag>
   <elementGuidId>6cd3ae0d-f23c-4039-bd29-4f4001a15e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtxContrasena_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtxContrasena_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b735e307-5033-41bd-91b2-83ae585aa117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys dxh0</value>
      <webElementGuid>219c7c7e-8605-47a2-a4b5-ffb9409b490a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtxContrasena_I</value>
      <webElementGuid>1dd9c0fb-aa25-4229-bc2d-45b5752cf5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtxContrasena</value>
      <webElementGuid>ae877839-c627-4b78-b774-4de61ca5f504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('txtxContrasena')</value>
      <webElementGuid>301dd772-7c9a-4957-ae41-b982dc0e7004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('txtxContrasena')</value>
      <webElementGuid>a8105ba1-e4f4-4b78-9aa1-b44475127604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxEValueChanged('txtxContrasena')</value>
      <webElementGuid>b00b9652-6482-4df0-9fe8-ed85b21bb3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>05c4f955-6897-4465-b2b2-443407025274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtxContrasena_I&quot;)</value>
      <webElementGuid>90a5e1bd-d4e0-428f-95c1-c001898da412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtxContrasena_I']</value>
      <webElementGuid>cfa367fa-7b8f-45e0-afdf-d527cc0017cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='txtxContrasena']/tbody/tr/td/input</value>
      <webElementGuid>7b9370ac-44d8-4650-bf3c-8a7273929968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>35b17c44-c86c-486f-9ef6-90d15ce71bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtxContrasena_I' and @name = 'txtxContrasena' and @type = 'password']</value>
      <webElementGuid>5605f3dc-f255-465b-b7d6-054645a07e68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
