<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Aguas Chaar</name>
   <tag></tag>
   <elementGuidId>6acc4b5b-7215-4707-9d55-0acc10ea6e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#xddlEmpresa_DDD_L_LBI4T0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xddlEmpresa_DDD_L_LBI4T0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>55f4a402-3ae8-437d-92ed-47613642123c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Office2010Blue dxeListBoxItemHover_Office2010Blue</value>
      <webElementGuid>3ccb7b7f-fb45-4ff5-9079-45f5834ae0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlEmpresa_DDD_L_LBI4T0</value>
      <webElementGuid>01e4e3ff-be8c-49b9-addd-6230bfe9bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aguas Chañar</value>
      <webElementGuid>bd3bf72c-93dc-40e5-bef3-6928fc92c7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlEmpresa_DDD_L_LBI4T0&quot;)</value>
      <webElementGuid>04140b31-41b2-419d-94af-78148f89b53c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xddlEmpresa_DDD_L_LBI4T0']</value>
      <webElementGuid>21cff7c0-a6d2-4ab2-aa96-589098dcd834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xddlEmpresa_DDD_L_LBT']/tbody/tr[5]/td</value>
      <webElementGuid>5ccbc7ce-f891-41c3-9314-82c32d9afff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aguas Magallanes'])[1]/following::td[1]</value>
      <webElementGuid>75ba2def-a233-4507-8059-088e5405fd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aguas del Altiplano'])[1]/following::td[2]</value>
      <webElementGuid>67fb8db5-52b3-41f9-826e-bfba938cb1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aguas Nuevas'])[1]/preceding::td[1]</value>
      <webElementGuid>fb24fd9a-9f33-4b03-834e-3fda00063e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EnerNuevas'])[1]/preceding::td[2]</value>
      <webElementGuid>1de7a9a7-3e4b-497b-a7e5-9b36a773e7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aguas Chañar']/parent::*</value>
      <webElementGuid>5f8602e6-0227-4010-ba38-f0264f937fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td</value>
      <webElementGuid>8eac6c0c-bda1-44d9-b8fd-281dd91c826e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xddlEmpresa_DDD_L_LBI4T0' and (text() = 'Aguas Chañar' or . = 'Aguas Chañar')]</value>
      <webElementGuid>688b2ecd-2c77-4de6-97f6-7d18344a0919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
