<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nueva Atacama</name>
   <tag></tag>
   <elementGuidId>fe97dfd2-8d85-4118-9731-a68baa73a187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xddlEmpresa_DDD_L_LBI4T0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlEmpresa_DDD_L_LBI4T0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>93264714-e087-436b-a816-97a49dcc3145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeListBoxItem_Office2010Blue dxeListBoxItemHover_Office2010Blue dxeListBoxItemSelected_Office2010Blue</value>
      <webElementGuid>5f528165-febc-4bfd-b30c-c75e7d0345c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlEmpresa_DDD_L_LBI4T0</value>
      <webElementGuid>cac8d669-4872-4d6a-904d-345eb3a616fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva Atacama</value>
      <webElementGuid>79d583ee-9207-4e12-9cbe-7c716c438e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlEmpresa_DDD_L_LBI4T0&quot;)</value>
      <webElementGuid>9995786d-5028-4cd8-8d86-2542917a8315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xddlEmpresa_DDD_L_LBI4T0']</value>
      <webElementGuid>e22f8616-52d6-4e23-b160-f457609a17ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xddlEmpresa_DDD_L_LBT']/tbody/tr[5]/td</value>
      <webElementGuid>a5e7f742-ac03-4879-bc73-3b1c7c8cbed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aguas Magallanes'])[1]/following::td[1]</value>
      <webElementGuid>92ca2bf5-0739-4d28-b64a-4d181f8c68d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aguas del Altiplano'])[1]/following::td[2]</value>
      <webElementGuid>21acc5b6-996b-4d9d-bc33-cac0208c8412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aguas Nuevas'])[1]/preceding::td[1]</value>
      <webElementGuid>3f6c6e10-227a-4551-8c70-3e8d22f1344e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EnerNuevas'])[1]/preceding::td[2]</value>
      <webElementGuid>bf693832-7f1f-424e-8e4e-214fd6b0887c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva Atacama']/parent::*</value>
      <webElementGuid>7f0fbe1d-2dc5-4242-9329-3e42bbabe79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td</value>
      <webElementGuid>0ed1aef8-2397-4da3-b53f-e9c15b29c9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xddlEmpresa_DDD_L_LBI4T0' and (text() = 'Nueva Atacama' or . = 'Nueva Atacama')]</value>
      <webElementGuid>2e365f80-3be8-4ab6-ae92-43624cc30ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
