<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_RDI5 - CONSUMO APv2</name>
   <tag></tag>
   <elementGuidId>5d007c7e-735a-434b-a604-f3afb01fd526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-11 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-11']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b4521f0-04b5-4fe2-869f-a12014946c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>c38956c1-1af7-4c3a-8a2f-664a7d8f42a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RDI5 - CONSUMO AP </value>
      <webElementGuid>a14eaaae-5ff9-45a1-83cf-23c01e86ac28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-11&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>4ddc76ec-4ed6-4a20-b290-43b89b7fd74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-11']/span</value>
      <webElementGuid>ef6e9165-d5e6-4e64-a3af-45951b170764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RDI3 - GRAFICA VARIABLES DISTRIBUCION'])[1]/following::span[1]</value>
      <webElementGuid>982e61bb-4244-4645-b06e-c9dfe1fe68e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RDI2 - VARIABLES DISTRIBUCION ERP'])[1]/following::span[2]</value>
      <webElementGuid>ac9c9d68-7b01-47d2-91b9-301514676b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RDI5 - CONSUMO AP']/parent::*</value>
      <webElementGuid>7941f97f-9592-4d3b-ada6-71f2e9bdbbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[5]/span</value>
      <webElementGuid>be8c67d4-fcaf-4506-966f-684c165ae06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' RDI5 - CONSUMO AP ' or . = ' RDI5 - CONSUMO AP ')]</value>
      <webElementGuid>d77e1e48-0d74-48e4-ae2f-8ca4cfc24b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
