<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , webviewer-1, , ))_webviewer-1</name>
   <tag></tag>
   <elementGuidId>1008fe14-7600-4361-91b7-af0c9dfdbb0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#webviewer-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='webviewer-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>webviewer-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vermont.aguasnuevas.cl/se/v96079/generic/app/pdftron/lib/./ui/index.html#d=https%3A%2F%2Fvermont.aguasnuevas.cl%2Fse%2Fv96079%2Ftemp%2Fb3db13f5-45e9-4ed0-a28d-f4602763f7f77864318318400073237.pdf&amp;extension=pdf&amp;pdf=ems&amp;office=ems&amp;streaming=true&amp;a=1&amp;readonly=1&amp;hideAnnotationPanel=1&amp;custom=%7B%22printPermission%22%3Afalse%2C%22savePermission%22%3Afalse%2C%22downPermission%22%3Afalse%2C%22know_permission%22%3Afalse%2C%22converted%22%3Afalse%2C%22isGoogleDriveEnabled%22%3Afalse%2C%22isMicrosoftOneDriveEnabled%22%3Afalse%2C%22isMobile%22%3Afalse%2C%22language%22%3A%22es%22%2C%22windowTitle%22%3A%22HTML5%20PDF%20Viewer%22%2C%22counterSignTerm%22%3A%22Conocimiento%20de%20publicaci%C3%B3n%22%2C%22hasCounterSign%22%3A%220%22%2C%22downloadPdfTerm%22%3A%22Descarga%20del%20PDF%22%2C%22downloadOriginalTerm%22%3A%22Descarga%20del%20archivo%20original%22%2C%22viewithGoogleDriveTerm%22%3A%22Visualizar%20archivo%20electr%C3%B3nico%20en%20Google%20Drive%22%2C%22viewithMicrosoftOneDriveTerm%22%3A%22Visualizar%20archivo%20electr%C3%B3nico%20en%20OneDrive%22%2C%22printTerm%22%3A%22Imprimir%22%2C%22publicationKnowledgeTerm%22%3A%22Confirmar%20conocimiento%20de%20publicaci%C3%B3n%22%2C%22visualizationScreenTerm%22%3A%22HTML5+PDF+Viewer%22%2C%22confirmPublicationKnowledgeTerm%22%3A%22%C2%BFDesea%20ejecutar%20el%20conocimiento%20de%20publicaci%C3%B3n%3F%22%2C%22taskAlreadyExecutedTerm%22%3A%22Tarea%20pendiente%20ya%20ejecutada%22%2C%22mustPreviewDocumentBeforeConfirmKnowledgeTerm%22%3A%22Todos%20los%20archivos%20electr%C3%B3nicos%20del%20documento%20deben%20ser%20visualizados%20antes%20de%20liberar%20la%20tarea.%22%2C%22uid%22%3A%22326%22%2C%22pathBase%22%3A%22https%3A%2F%2Fvermont.aguasnuevas.cl%2Fse%2Fv96079%2F%22%2C%22cddocument%22%3A%224412%22%2C%22cdrevision%22%3A%22%22%2C%22revCommentVer%22%3A%221.0%22%2C%22action%22%3A4%7D&amp;filepicker=0&amp;pdfnet=0&amp;enableRedaction=0&amp;enableMeasurement=0&amp;toolbar=true&amp;pageHistory=1&amp;notesInLeftPanel=0&amp;singleServerMode=false&amp;selectAnnotationOnCreation=0&amp;id=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>webviewer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webviewer-1&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Documento (DC021) - Documento/iframe_Archivo_iframe_abas</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='webviewer-1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewer']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
   </webElementXpaths>
</WebElementEntity>
