<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_daniela.guerras.dggmail.com</name>
   <tag></tag>
   <elementGuidId>6f66148c-49a1-4de5-a7ca-11b2e39ca06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='xgrwRegistroWeb_DXDataRow0']/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>19ad2049-a7ca-4b45-8f73-09e854ba7624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxgv</value>
      <webElementGuid>ffae8c6e-f38b-4351-95c9-243d16085fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>daniela.guerras.dg@gmail.com</value>
      <webElementGuid>3c33ffa4-abe5-4d60-9b3a-45fc04e53acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xgrwRegistroWeb_DXDataRow0&quot;)/td[@class=&quot;dxgv&quot;]</value>
      <webElementGuid>2a380cdb-5344-493c-8dfc-ee83cb4f4db8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='xgrwRegistroWeb_DXDataRow0']/td[3]</value>
      <webElementGuid>999785ef-aca5-47c5-8b25-ab5d2dac3821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DANIELA'])[1]/following::td[1]</value>
      <webElementGuid>9349be9e-65ef-443a-9209-072378fe0da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha inf. adicional'])[1]/following::td[14]</value>
      <webElementGuid>41ba7b7f-49e8-478b-8bc2-e16cbba27660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::td[2]</value>
      <webElementGuid>274d3a11-60c5-40b9-b406-a32e47070c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[2]/preceding::td[4]</value>
      <webElementGuid>0f401f8f-ec9d-4495-a9bc-836479c91044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='daniela.guerras.dg@gmail.com']/parent::*</value>
      <webElementGuid>d29dd8a0-eda2-43ff-acc3-d8ca158baa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>fbc5317a-5a07-43ec-baa7-910018502cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'daniela.guerras.dg@gmail.com' or . = 'daniela.guerras.dg@gmail.com')]</value>
      <webElementGuid>374e1024-5175-49a3-b312-cf8c9861d289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
