<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administracin1</name>
   <tag></tag>
   <elementGuidId>b87827bd-7fed-4c03-9ab8-32ddfa1950ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_Header1_xmenMenuHor_DXI0_T']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dx-vam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e20eb1d-b5f3-481e-abb9-ac29f03e4c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-vam</value>
      <webElementGuid>d65659f3-96a3-4566-a9ea-524132f571e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administración</value>
      <webElementGuid>709717c7-e07e-4f3d-ab5e-56f48d37e487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Header1_xmenMenuHor_DXI0_T&quot;)/span[@class=&quot;dx-vam&quot;]</value>
      <webElementGuid>25ef1050-74a9-467c-bfa6-c5187c0d5ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_Header1_xmenMenuHor_DXI0_T']/span</value>
      <webElementGuid>a3529671-3535-410b-be2c-72d37a25d670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Rol: Administrador] [Usuario(a): Gonzalez Gutierrez Luis Marcelo]'])[1]/following::span[1]</value>
      <webElementGuid>921bdd7e-4dc0-42fa-975f-d2452473d61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambiente de QA'])[1]/following::span[2]</value>
      <webElementGuid>44aa3e28-64cd-4c24-9623-d49d4751a21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eventos Masivos'])[1]/preceding::span[1]</value>
      <webElementGuid>27673d87-8217-4851-b2ba-1f6b44f3aedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultas'])[1]/preceding::span[2]</value>
      <webElementGuid>84884110-299f-44da-a0a0-fbffa6cac9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administración']/parent::*</value>
      <webElementGuid>214d6ee0-ed85-4094-99d2-3dc7ad512cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span</value>
      <webElementGuid>a178cc64-5c48-42c3-bed5-5d3b0550d72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Administración' or . = 'Administración')]</value>
      <webElementGuid>b5d38231-f302-4ebb-985d-05655bd641f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
