<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Cerrar Ventana Emergente</name>
   <tag></tag>
   <elementGuidId>9dd9adc6-c65f-459d-9b9e-408ba693c569</elementGuidId>
   <imagePath>../../Pictures/Captura de pantalla 2022-05-27 025038.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Pictures/Captura de pantalla 2022-05-27 025038.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ms-crm-Dialog-Error-Body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;butBegin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-Dialog-Error-Body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Existen mensajes de correo sin enviar con más de 24 horas de antigüedad. Para enviar estos mensajes, inicie sesión en Microsoft Dynamics 365 para Outlook o compruebe con el administrador del sistema que sincronización del lado del servidor o E-mail Router se haya configurado para enviar mensajes en su nombre. Para obtener más información sobre la configuración de correo, vea la Ayuda en pantalla.
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divWarning&quot;)/table[@class=&quot;ms-crm-Dialog-Error&quot;]/tbody[1]/tr[2]/td[@class=&quot;ms-crm-Dialog-Error-Body&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_rdenes de Trabajo Todas las Ordenes de Trabajos ltimos 6 meses - Microsoft Dynamics 365/iframe_Cargando_InlineDialog_Iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divWarning']/table/tbody/tr[2]/td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertencia de correo pendiente'])[1]/following::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar'])[1]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerrar']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
