<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AutentificacinUnificada_UserName (1)</name>
   <tag></tag>
   <elementGuidId>0f5b86e3-1a52-4785-b783-ce81568e6e10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userNameInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userNameInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43f6ef52-acb7-4aa1-a703-7bde16b89f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userNameInput</value>
      <webElementGuid>bfcd84fb-7fec-486d-9c75-f0fbe6624c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>86676fa2-9418-496b-a72b-11d9aaa20843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9dc083bb-7fce-492f-ad20-db0df90b3422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1dc76abd-0bde-44a8-b2d1-bbcd75adbf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text fullWidth</value>
      <webElementGuid>d6d9fa05-be60-49b3-a8aa-7ef24eb913da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa186e10-6178-4c8d-bfe2-feb9f116c268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>11111111-1</value>
      <webElementGuid>9dc30503-5446-4cb3-87d7-296d70d1d7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e9362aa-3623-42c9-8f40-6a05e4959cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userNameInput&quot;)</value>
      <webElementGuid>b08cf1e9-fe8f-4ab3-8c80-dd0310b39b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userNameInput']</value>
      <webElementGuid>9c8a99ee-0241-4df9-a86f-a9ffc18c75ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userNameArea']/input</value>
      <webElementGuid>808a3865-1ed5-42f9-b985-904b80cc92fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e12461ee-0182-4e2c-8e25-01a543157cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userNameInput' and @name = 'UserName' and @type = 'email' and @placeholder = '11111111-1']</value>
      <webElementGuid>ac962d87-a0bd-40ff-99e9-a0c43b992280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
