<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ciclo_xddlCicloEscribir</name>
   <tag></tag>
   <elementGuidId>5f003483-141a-4f54-9eec-5817c07f672d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='xddlCiclo_I']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xddlCiclo_I</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d41e0f5-b31e-424a-9c6e-7e48a8be8a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_Office2010Blue dxeEditAreaSys</value>
      <webElementGuid>ad2f2457-2651-4ed2-a554-13c34df1b799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xddlCiclo_I</value>
      <webElementGuid>c2d4db2a-3236-4933-8a8d-71627c243bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xddlCiclo</value>
      <webElementGuid>c30e51e0-208e-42bf-891a-f7d6d57d3f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>aspxEGotFocus('xddlCiclo')</value>
      <webElementGuid>027611b4-efcd-430c-ad93-1fc33e70c9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>aspxELostFocus('xddlCiclo')</value>
      <webElementGuid>d3315982-7da4-447f-ba5d-66ab23dce781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>aspxETextChanged('xddlCiclo')</value>
      <webElementGuid>5df926dc-1984-497f-861b-0be8ba706de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ciclo 342- (202205)</value>
      <webElementGuid>8dcf0d2e-7d89-4724-a04c-98f4e7363125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>364cbba1-87cf-4cde-a3cb-b77e395d5ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3da5efa6-4742-448d-8b01-7c72a2d4cd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xddlCiclo_I&quot;)</value>
      <webElementGuid>3c0cbf98-3646-435d-9fec-0a6635cc11e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='xddlCiclo_I']</value>
      <webElementGuid>577f627c-b70b-450c-a9ff-2de0eefc4cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='xddlCiclo']/tbody/tr/td[2]/input</value>
      <webElementGuid>dff87a86-d27a-4d35-b32c-c447179e58ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>8333b8b8-f8d4-452c-80ea-f67209748229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'xddlCiclo_I' and @name = 'xddlCiclo' and @type = 'text']</value>
      <webElementGuid>6a667145-b50a-4c15-b8ee-a0851f8eaf84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
