<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>becae676-96d1-4834-b830-de5c1d25347d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00xContentPlaceHolder1xUltraWebGrid1_l_0 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='ctl00xContentPlaceHolder1xUltraWebGrid1_l_0']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/WebResource.axd?d=MPxG2NNcosDGJ0uufiuuOWofr7evlXIXMcNkGUv9dIDS2-6HaneCZH_JMfMDLbtZCbcfcczW-LHcOU-z4Iu44RUTwEhu6lPZ0CN4eIYS7r-pa0gLxkrcTP1HT3fhSCGh8QyRphmpauge7QNtSEywQ_If6HyoNu-hQJkEiiBwh95yOPXgtRSHdTjwICe3eJ_LSI2ukw2&amp;t=634588205760000000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>imgtype</name>
      <type>Main</type>
      <value>tri</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00xContentPlaceHolder1xUltraWebGrid1_l_0&quot;)/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='ctl00xContentPlaceHolder1xUltraWebGrid1_l_0']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th/img</value>
   </webElementXpaths>
</WebElementEntity>
