<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Informes (1)</name>
   <tag></tag>
   <elementGuidId>df49008f-68dc-4802-874a-309232575dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_xcpnMenu_xmenMenuHor_DXI2_T']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_xcpnMenu_xmenMenuHor_DXI2_T</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>319f9ed4-bd10-481e-9eb1-703ef54790d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxm-content dxm-hasText </value>
      <webElementGuid>d8d67ef7-aac2-4918-979c-01ffc176e64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_xcpnMenu_xmenMenuHor_DXI2_T</value>
      <webElementGuid>b61d9974-aae1-4a70-8c89-a145dd9ed4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Informes
			</value>
      <webElementGuid>95b74d5a-448b-4aac-9f68-f629cda3893c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_xcpnMenu_xmenMenuHor_DXI2_T&quot;)</value>
      <webElementGuid>f23bcbb6-03d2-42de-9791-6debd93c8944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl00_xcpnMenu_xmenMenuHor_DXI2_T']</value>
      <webElementGuid>628c402e-85ff-496d-89b8-4e953be1306f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ctl00_xcpnMenu_xmenMenuHor_DXI2_']/div</value>
      <webElementGuid>4a78c572-e1c0-482f-99cf-cadc10b71458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operaciones'])[1]/following::div[2]</value>
      <webElementGuid>e4418858-8559-49b5-b6b7-c70aed5a9d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceso'])[1]/following::div[4]</value>
      <webElementGuid>20f95071-d07e-459d-9000-7896868b18dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspecciones'])[1]/preceding::div[2]</value>
      <webElementGuid>88036123-2869-45f2-a03d-f3955f0ec372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div</value>
      <webElementGuid>51b80d95-4fe5-4242-9ae2-8aeea16e0b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl00_xcpnMenu_xmenMenuHor_DXI2_T' and (text() = '
				Informes
			' or . = '
				Informes
			')]</value>
      <webElementGuid>8a59b5a3-6637-43d7-814c-e5b17c7be116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
