<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Eventos Masivos (1)</name>
   <tag></tag>
   <elementGuidId>8e402871-deee-4b0e-aae5-51ec4e2fd3f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alb_ele_27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='alb_ele_27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>99772411-7237-4461-aec9-8fa97845bc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>c6260a40-fbce-44a8-93ba-76796b166a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>75981744-43aa-4829-ad19-3e31870803d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>2b3d250d-cb6c-47e2-852a-5723b0b46675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alb_css_menu_ctl00_Header1_WebAguasControlMenu11</value>
      <webElementGuid>ecf74a53-1fca-41a8-be59-dbaf8b47e981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alb_ele_27</value>
      <webElementGuid>25879952-b05b-4de3-81bd-cfe3e1cf496d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eventos Masivos</value>
      <webElementGuid>78de7523-c1e0-4738-b66d-b11e32701c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alb_ele_27&quot;)</value>
      <webElementGuid>b6b8133d-57ee-4b51-825d-fdde26e70f7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='alb_ele_27']</value>
      <webElementGuid>17657210-e5c6-442d-a73e-bfbd7ae22445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='alb_ele_1']/tbody/tr/td/table/tbody/tr/td[3]</value>
      <webElementGuid>a881b9de-bec9-40f3-9fd2-0b0cf5b50126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administración'])[1]/following::td[2]</value>
      <webElementGuid>47d6f819-dc1c-410b-8a6f-0cdf8d4f47a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Rol: Administrador] [Usuario(a): De Prueba Usuario]'])[1]/following::td[5]</value>
      <webElementGuid>6fd006e0-cd23-4ef5-906d-b4b457a654ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos Cliente'])[1]/preceding::td[2]</value>
      <webElementGuid>be1b827b-da36-4e0b-b8e2-fb4be821a07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/table/tbody/tr/td[3]</value>
      <webElementGuid>b6faae10-d5d4-40b6-a501-14a094c9f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'alb_ele_27' and (text() = 'Eventos Masivos' or . = 'Eventos Masivos')]</value>
      <webElementGuid>0cba0911-5706-4f3c-8f5f-c8dc8febe423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
