<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Listar (1)</name>
   <tag></tag>
   <elementGuidId>a70e77eb-bd2a-4883-bdf3-57f4ba2bd27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alb_ele_26</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='alb_ele_26']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>336f9ed9-f623-44fb-acf7-81068c8c0430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>b05d2ecf-b09c-4760-9536-b3f57500ab97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>693396a0-7c9e-494d-81b4-626163b68cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>a7e146b1-4b2b-4003-85b0-60c60df47f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alb_ele_26</value>
      <webElementGuid>ab2c13f3-f5ed-4a31-a3a9-3e9bb7910cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alb_css_menu_ctl00_Header1_WebAguasControlMenu17</value>
      <webElementGuid>e12c78a1-4bef-4c07-b4f2-0b28e3404752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listar</value>
      <webElementGuid>b9ba5099-0a76-4eb0-80db-cb4577d5f759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alb_ele_26&quot;)</value>
      <webElementGuid>5734e6d3-4be4-450c-86f3-992b42dc0d2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='alb_ele_26']</value>
      <webElementGuid>36c97c03-29e6-4ec9-9b65-b4b6564abf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='alb_ele_25']/tbody/tr/td/table/tbody/tr/td</value>
      <webElementGuid>65edaab1-e04a-47e1-a6dd-89fcb4e7645c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuración Horas Aviso Envio'])[1]/following::td[2]</value>
      <webElementGuid>e17b075d-9a75-4eea-9e4e-200548b2f937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes Email'])[1]/following::td[4]</value>
      <webElementGuid>966f4749-9baa-4600-b88b-180ee06053e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestión'])[1]/preceding::td[1]</value>
      <webElementGuid>f2defad9-525b-43d7-94ca-d4e0a8ccf0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td/table/tbody/tr/td</value>
      <webElementGuid>40654e35-9653-469c-859d-cfe0827d146d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'alb_ele_26' and (text() = 'Listar' or . = 'Listar')]</value>
      <webElementGuid>ecc6be47-ac96-49fa-916d-dc13e60821f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
