<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Nuevo portal de SE Suite_seicon-cancel</name>
   <tag></tag>
   <elementGuidId>313358e5-b1df-4e5f-a622-5a7b3be88ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@onclick='Onboarding.activeTour.complete()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.seicon-cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seicon-cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Onboarding.activeTour.complete()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;se-body shepherd-active shepherd-target shepherd-element-attached-middle shepherd-element-attached-center shepherd-target-attached-middle shepherd-target-attached-center shepherd-enabled shepherd-over-overlay&quot;]/div[@class=&quot;shepherd-step shepherd-theme-arrows hide-onboarding-arrow hide-onboarding-workspace shepherd-onboarding-workspace shepherd-has-title shepherd-element shepherd-element-attached-middle shepherd-element-attached-center shepherd-target-attached-middle shepherd-target-attached-center shepherd-open shepherd-enabled&quot;]/div[@class=&quot;shepherd-content&quot;]/header[1]/h3[@class=&quot;shepherd-title&quot;]/i[@class=&quot;seicon-cancel&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@onclick='Onboarding.activeTour.complete()']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/i</value>
   </webElementXpaths>
</WebElementEntity>
