<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cargando_xdocView_Splitter_Viewer_Co_be9726 (1)</name>
   <tag></tag>
   <elementGuidId>08c13d92-5aa3-4c7f-a123-9681d1799cfc</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>72daa970-7c05-4d09-a84d-56e0f600b4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xdocView_Splitter_Viewer_ContentFrame</value>
      <webElementGuid>50a962a9-c7b1-4b29-a643-2fe7b550a64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>xdocView_Splitter_Viewer_ContentFrame</value>
      <webElementGuid>cc822700-a34b-41f2-9a57-45297da5a3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8533dc6-9b9a-4e06-a211-89073dab2767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xdocView_Splitter_Viewer_ContentFrame&quot;)</value>
      <webElementGuid>02814a7d-d1cd-4c6a-b1cb-c01c7184147b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='xdocView_Splitter_Viewer_ContentFrame']</value>
      <webElementGuid>dedc1297-7504-4375-9c4c-6f79455225ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xdocView_Splitter_Viewer_Div']/iframe</value>
      <webElementGuid>90435f9b-9210-4994-9457-207e01e3658a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>724c92b5-b1e1-421a-a2f0-ad3c1e41f483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'xdocView_Splitter_Viewer_ContentFrame' and @name = 'xdocView_Splitter_Viewer_ContentFrame']</value>
      <webElementGuid>9fd869cb-5bad-48fc-aeb7-7255fd72e9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
