<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_26</name>
   <tag></tag>
   <elementGuidId>d18f20a3-6a11-4926-9ceb-37f6e846f4a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='content']/table/tbody/tr[7]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da1c18c5-ccf6-4566-962f-6a77d236cbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>window.status=&quot;Select 26/04/2022 as date.&quot;</value>
      <webElementGuid>f6a4a05b-a7e6-4420-9b3a-113614a8ec79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>window.status=&quot;&quot;</value>
      <webElementGuid>44827030-eea4-49fd-9f5d-684fc7a89567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:dateSelected=26;closeCalendar();</value>
      <webElementGuid>7fee11bd-74e2-4f1d-9efe-73bae8ccad6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 26 </value>
      <webElementGuid>38299f95-354a-45a4-a5c1-db21204854b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/table[1]/tbody[1]/tr[7]/td[2]/a[1]</value>
      <webElementGuid>ca0b0aea-353b-4203-83db-bb639e2781c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='content']/table/tbody/tr[7]/td[2]/a</value>
      <webElementGuid>2512c3e6-07f4-4936-a5a2-5ece65812537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'26')]</value>
      <webElementGuid>f107c075-cd1e-4c3f-9edb-2b13222efea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dom'])[1]/following::a[26]</value>
      <webElementGuid>b7b39bc1-aae6-4340-a4e9-990b26aefec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sab'])[1]/following::a[26]</value>
      <webElementGuid>6956e74b-c1fa-459b-9bfe-9ae3a1ce0823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:dateSelected=26;closeCalendar();')]</value>
      <webElementGuid>f0eea26b-ad5c-48f0-915d-79af0bb2fecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/a</value>
      <webElementGuid>9b14672c-1fdc-404e-9e78-a5ffb35b91bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:dateSelected=26;closeCalendar();' and (text() = ' 26 ' or . = ' 26 ')]</value>
      <webElementGuid>31096e5a-bb8c-40c7-8a81-15f819b02f6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
