<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_F. Inicio Planificado_imgCal</name>
   <tag></tag>
   <elementGuidId>333d4a34-0a54-42fe-a2ee-93546a95b8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.imgCal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick=&quot;javascript:popUpCalendar(this,document.getElementById('ctl00_ContentPlaceHolder1_txtFechaInicio_txtdate'),'dd/mm/yyyy',0,0);&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fabdc952-e652-4fa2-a29d-fbd9dd197717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgCal</value>
      <webElementGuid>7cfbc778-6340-4f2a-98a2-816e3e5747a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:popUpCalendar(this,document.getElementById('ctl00_ContentPlaceHolder1_txtFechaInicio_txtdate'),'dd/mm/yyyy',0,0);</value>
      <webElementGuid>fbc9f8a8-dffa-4529-9c49-364079c4801d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>js/pop_calendar/img1/cal.gif</value>
      <webElementGuid>6127911c-3263-4ded-89a0-f3ea9a8c5c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_txtFechaInicio&quot;)/img[@class=&quot;imgCal&quot;]</value>
      <webElementGuid>39965408-61db-4cfc-9999-73b259fab343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick=&quot;javascript:popUpCalendar(this,document.getElementById('ctl00_ContentPlaceHolder1_txtFechaInicio_txtdate'),'dd/mm/yyyy',0,0);&quot;]</value>
      <webElementGuid>a126087a-e351-40e3-87d9-65825b9cd5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder1_txtFechaInicio']/img</value>
      <webElementGuid>bcee0791-88e4-4923-82f5-04dfba586b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span/img</value>
      <webElementGuid>40882533-8768-4047-95eb-42a2f8a69fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'js/pop_calendar/img1/cal.gif']</value>
      <webElementGuid>6b1e7c68-a62a-4a0c-bd9c-aeca4610dee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
