<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nobr_Araucana (1)</name>
   <tag></tag>
   <elementGuidId>5ff4583d-524f-47ce-be7b-4583b435ff03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ctl00xContentPlaceHolder1xuwgListado_r_0']/td[8]/nobr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nobr</value>
      <webElementGuid>32b1d5fa-287f-4ae4-8b7a-b0f2dde0015b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Araucanía</value>
      <webElementGuid>99143550-c056-45c5-8e4b-d76df4d631d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00xContentPlaceHolder1xuwgListado_r_0&quot;)/td[@class=&quot;ig_166b4a06_r1&quot;]/nobr[1]</value>
      <webElementGuid>db0782e0-e2dd-4fd0-8420-a60387edfb51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ctl00xContentPlaceHolder1xuwgListado_r_0']/td[8]/nobr</value>
      <webElementGuid>d90fb93b-b6d4-43af-b92e-1a103922841e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digitado'])[2]/following::nobr[1]</value>
      <webElementGuid>874ccfa6-b37a-4967-a902-e9f1e0e69171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[4]/following::nobr[2]</value>
      <webElementGuid>b7511457-79b7-4088-9f4d-ed0fa1c4f703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temuco'])[2]/preceding::nobr[1]</value>
      <webElementGuid>d55dfa38-c689-45be-9cbb-9f1a5a837e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corte Programado'])[2]/preceding::nobr[2]</value>
      <webElementGuid>690a4882-33a7-4185-ab38-e238ded12c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/nobr</value>
      <webElementGuid>5f9e7161-b186-4e9e-9499-d6709e846d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nobr[(text() = 'Araucanía' or . = 'Araucanía')]</value>
      <webElementGuid>367ab745-b528-431d-bd4d-629fea7adc00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
