<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Junio</name>
   <tag></tag>
   <elementGuidId>a02f40d4-40d0-42c4-93c3-ed9df345a1d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb25cb2c-e9ed-43ec-9170-1dd3f16f17ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanMonth</value>
      <webElementGuid>c1d71c71-8434-473a-a62a-2d275b1156ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>swapImage(&quot;changeMonth&quot;,&quot;drop2.gif&quot;);this.style.borderColor=&quot;#9CBDF0&quot;;window.status=&quot;Click to select a month.&quot;</value>
      <webElementGuid>524e3824-4ab8-4fbd-bb45-dbbbff12daaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>swapImage(&quot;changeMonth&quot;, &quot;drop1.gif&quot;);this.style.borderColor=&quot;#8EB1E9&quot;;window.status=&quot;&quot;</value>
      <webElementGuid>f579f24b-1f72-419a-a704-d96e15c82377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>popUpMonth()</value>
      <webElementGuid>363b7401-b673-4b55-82d1-b6e745ed5295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Junio </value>
      <webElementGuid>d7e66ac2-1797-4a60-b927-5182ebd55cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanMonth&quot;)</value>
      <webElementGuid>e1f3390f-12a9-4ec5-b59f-f3845c0c2281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanMonth']</value>
      <webElementGuid>03695ec8-5981-4bd3-af52-b53355ad2fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='caption']/span[3]</value>
      <webElementGuid>1fa87535-3f88-4d5a-b6cf-111228c73c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Problema Masivo'])[1]/following::span[4]</value>
      <webElementGuid>3cf19805-c997-4cc5-be9e-4419bcf4adfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporte Clientes con Despacho Electrónico'])[1]/following::span[4]</value>
      <webElementGuid>16e00240-c3ca-4c1a-a727-cbe790810993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lun'])[1]/preceding::span[2]</value>
      <webElementGuid>49dfcb04-053b-49a4-8620-3eb908de1a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar'])[1]/preceding::span[2]</value>
      <webElementGuid>a2de060e-7e8d-4809-b2b1-80fc76aaafeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>2f49430e-6e8d-4c8e-884e-a51c9624411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanMonth' and (text() = ' Junio ' or . = ' Junio ')]</value>
      <webElementGuid>3a0107a5-27ac-450c-b319-20a7ceabaa65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
