<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Abril</name>
   <tag></tag>
   <elementGuidId>a0e15276-8187-47f6-aaba-791daeccd86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='m3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e1709ea4-566e-43d1-9920-6db7398f39ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m3</value>
      <webElementGuid>7e89a981-172a-4b5b-a810-23c6f00f8b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.style.backgroundColor=&quot;#B4CDF5&quot;</value>
      <webElementGuid>3251f900-e1a1-4b3e-b060-220166e500a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.style.backgroundColor=&quot;&quot;</value>
      <webElementGuid>ef8afc77-3683-42d8-a523-384899dd3cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>monthConstructed=false;monthSelected=3;constructCalendar();popDownMonth();event.cancelBubble=true</value>
      <webElementGuid>230b8ce0-32c8-463e-ba5c-bc4f92b63eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Abril </value>
      <webElementGuid>7393274c-6721-4891-b366-d41d61ca8a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m3&quot;)</value>
      <webElementGuid>aeb9a9ed-42c1-4f5b-b52c-8949ace14756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='m3']</value>
      <webElementGuid>837962c4-d89f-4fa5-b52d-1830610be299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selectMonth']/table/tbody/tr[4]/td</value>
      <webElementGuid>7ddbd26d-83da-4e44-865f-456d350a80e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Junio'])[1]/preceding::td[2]</value>
      <webElementGuid>69ba2408-aaea-44d7-b108-65d861f41aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr[4]/td</value>
      <webElementGuid>61624bde-e71a-45ef-a4d1-0ef717ee51b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'm3' and (text() = ' Abril ' or . = ' Abril ')]</value>
      <webElementGuid>353d145c-ca0a-4092-b746-94ef5ad8a7a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
