<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Evaluador Estndar_pe pe-7s-users text-info pe-2x</name>
   <tag></tag>
   <elementGuidId>42bee1b9-4c46-44a2-8d22-27f518044db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.pe.pe-7s-users.text-info.pe-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/nav/div[5]/ul/li/div/div/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pe pe-7s-users text-info pe-2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[1]/div[@class=&quot;navbar-right tour-2&quot;]/ul[@class=&quot;nav navbar-nav no-borders&quot;]/li[@class=&quot;dropdown open&quot;]/div[@class=&quot;dropdown-menu hdropdown bigmenu animated flipInX&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[1]/i[@class=&quot;pe pe-7s-users text-info pe-2x&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/nav/div[5]/ul/li/div/div/div[3]/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
   </webElementXpaths>
</WebElementEntity>
